export const constants: {[id: string] : string;} = {
    DATABASE_CONNECTION: 'DATABASE_CONNECTION',
    TERRITORY_REPOSITORY: 'TERRITORY_REPOSITORY',
    SQUARE_REPOSITORY: 'SQUARE_REPOSITORY',
    ERROR_REPOSITORY: 'ERROR_REPOSITORY',
    DOMAIN_ERROR_REPOSITORY: 'DOMAIN_ERROR_REPOSITORY',
    TYPE_ERROR_REPOSITORY: 'TYPE_ERROR_REPOSITORY',
}